force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>Overall balance of the account.</description>
    <formula>(Total_Income__c +  Total_Transfers_In__c) - (Total_Expenses__c + Total_Transfers_Out__c + Total_Card_Charges__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Balancing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balancing_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount to offset calculations by for the balance total due to omitted or previously removed transfer, expense, or income records.(i.e. initial balance, balance after removing old records to clear up storage, etc.)</description>
    <label>Balancing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Card_Charges__c.field-meta.xml
<CustomField>
    <fullName>Total_Card_Charges__c</fullName>
    <description>Total paid off charges to credit cards from the account.</description>
    <label>Total Card Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Charges_Stricken__c.field-meta.xml
<CustomField>
    <fullName>Total_Charges_Stricken__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total amount of charges to the credit card that were stricken for a fraudulent or challenged charge.</description>
    <label>Total Charges Stricken</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_In__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_In__c</fullName>
    <label>Total Transfers In</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_Out__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_Out__c</fullName>
    <label>Total Transfers Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/General_Equity.recordType-meta.xml
<RecordType>
    <fullName>General_Equity</fullName>
    <active>true</active>
    <label>General Equity</label>
</RecordType>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <description>A record that does not indicate an expense incurred or income received but which facilitates a balance transfer from one account to another.</description>
    <label>Transfer</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of the transfer.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Withdrawal</fullName>
            </value>
            <value>
                <fullName>Online Transfer</fullName>
            </value>
            <value>
                <fullName>Venmo Transfer</fullName>
            </value>
            <value>
                <fullName>Card Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Source_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outbound Transfers</relationshipLabel>
    <relationshipName>Outbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Target_Account__c.field-meta.xml
<CustomField>
    <fullName>Target_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbound Transfers</relationshipLabel>
    <relationshipName>Inbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer__c/recordTypes/Card_Payoff.recordType-meta.xml
<RecordType>
    <fullName>Card_Payoff</fullName>
    <active>true</active>
    <description>A payment of a credit card to reduce both the card&apos;s balance and the target account&apos;s.</description>
    <label>Card Payoff</label>
</RecordType>

force-app/main/default/objects/Transfer__c/recordTypes/Lateral_Transfer.recordType-meta.xml
<RecordType>
    <fullName>Lateral_Transfer</fullName>
    <active>true</active>
    <description>A lateral transfer from one balance to another; no credit card involved.</description>
    <label>Lateral Transfer</label>
</RecordType>

force-app/main/default/classes/TransferTriggerControllerTest.cls
@IsTest
public class TransferTriggerControllerTest {
  @isTest
  static void insertTransfersTest() {
    Map<String, Transfer__c> transferMap = TestDataFactory.createTransfers();

    Test.startTest();
    System.runAs(new User(Id = UserInfo.getUserId())) {
      insert transferMap.values();
    }
    Test.stopTest();

    Map<String, Account> updatedAccounts = getUpdatedAccounts();

    assertAccountSubtotals(
      updatedAccounts.get('test_checking'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 30,
        'Total_Transfers_Out__c' => 25,
        'Total_Card_Charges__c' => 20,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 85
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_savings'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 10,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 110
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_cash'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 15,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 115
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_card'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 20,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 25,
        'Balance__c' => 55
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_digital'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 30,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 70
      }
    );

    Assert.isTrue(true, 'all asserts have passed, satisfy PMD');
  }

  @isTest
  static void updateTransfersTest() {
    User testUser = new User(Id = UserInfo.getUserId());
    Map<String, Transfer__c> transferMap = TestDataFactory.createTransfers();
    System.runAs(testUser) {
      insert new List<Transfer__c>{
        transferMap.get('checking_to_savings'),
        transferMap.get('atm_withdrawal')
      };
    }

    Account newTestCheckingAccount = new Account(
      Type = 'Checking Account',
      Name = 'new_test_checking',
      RecordTypeId = TestDataFactory.accountRecordTypes.get('General_Equity'),
      Balancing_Amount__c = 100,
      Total_Transfers_In__c = 0,
      Total_Transfers_Out__c = 0,
      Total_Card_Charges__c = 0,
      Total_Charges_Stricken__c = 0
    );
    insert newTestCheckingAccount;
    transferMap.get('checking_to_savings')
      .Source_Account__c = newTestCheckingAccount.Id;
    transferMap.get('atm_withdrawal').Amount__c = 45;

    Test.startTest();
    System.runAs(testUser) {
      update new List<Transfer__c>{
        transferMap.get('checking_to_savings'),
        transferMap.get('atm_withdrawal')
      };
    }
    Test.stopTest();

    Map<String, Account> updatedAccounts = getUpdatedAccounts();

    assertAccountSubtotals(
      updatedAccounts.get('test_checking'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 45,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 55
      }
    );
    assertAccountSubtotals(
      updatedAccounts.get('new_test_checking'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 10,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 90
      }
    );
    assertAccountSubtotals(
      updatedAccounts.get('test_cash'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 45,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 145
      }
    );

    Assert.isTrue(true, 'all asserts have passed, satisfy PMD');
  }

  @isTest
  static void deleteTransfersTest() {
    User testUser = new User(Id = UserInfo.getUserId());
    Map<String, Transfer__c> transferMap = TestDataFactory.createTransfers();
    System.runAs(testUser) {
      insert transferMap.values();
    }

    Map<String, Account> accountMap = getUpdatedAccounts();

    System.runAs(testUser) {
      insert new List<Transfer__c>{
        new Transfer__c(
          Subject__c = 'new_card_payoff',
          RecordTypeId = TestDataFactory.transferRecordTypes.get('Card_Payoff'),
          Amount__c = 55,
          Method__c = 'Card Payoff',
          Source_Account__c = accountMap.get('test_checking').Id,
          Target_Account__c = accountMap.get('test_card').Id
        ),
        new Transfer__c(
          Subject__c = 'new_venmo_transfer',
          RecordTypeId = TestDataFactory.transferRecordTypes.get(
            'Lateral_Transfer'
          ),
          Amount__c = 65,
          Method__c = 'Venmo Transfer',
          Source_Account__c = accountMap.get('test_digital').Id,
          Target_Account__c = accountMap.get('test_savings').Id
        )
      };
    }

    accountMap = getUpdatedAccounts();

    assertAccountSubtotals(
      accountMap.get('test_checking'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 30,
        'Total_Transfers_Out__c' => 25,
        'Total_Card_Charges__c' => 75,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 30
      }
    );

    assertAccountSubtotals(
      accountMap.get('test_savings'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 75,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 175
      }
    );

    assertAccountSubtotals(
      accountMap.get('test_cash'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 15,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 115
      }
    );

    assertAccountSubtotals(
      accountMap.get('test_card'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 75,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 25,
        'Balance__c' => 0
      }
    );

    assertAccountSubtotals(
      accountMap.get('test_digital'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 95,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 5
      }
    );

    Test.startTest();
    System.runAs(testUser) {
      delete new List<Transfer__c>{
        transferMap.get('card_payoff'),
        transferMap.get('venmo_transfer')
      };
    }
    Test.stopTest();
    Assert.areEqual(
      5,
      [SELECT COUNT() FROM Transfer__c],
      'count of total transfer records'
    );

    Map<String, Account> updatedAccounts = getUpdatedAccounts();

    assertAccountSubtotals(
      updatedAccounts.get('test_checking'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 25,
        'Total_Card_Charges__c' => 55,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 20
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_card'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 55,
        'Total_Transfers_Out__c' => 0,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 25,
        'Balance__c' => 20
      }
    );

    assertAccountSubtotals(
      updatedAccounts.get('test_digital'),
      new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Total_Transfers_In__c' => 0,
        'Total_Transfers_Out__c' => 65,
        'Total_Card_Charges__c' => 0,
        'Total_Charges_Stricken__c' => 0,
        'Balance__c' => 35
      }
    );

    Assert.isTrue(true, 'all asserts have passed, satisfy PMD');
  }

  /**
   * @param Account
   * @param expectedTotals (Map<String, Double>)
   */
  private static void assertAccountSubtotals(
    Account a,
    Map<String, Double> expectedTotals
  ) {
    for (String s : expectedTotals.keySet()) {
      Assert.areEqual(
        expectedTotals.get(s),
        a.get(s),
        'field: ' + s + ' for account: ' + a
      );
    }
  }

  private static Map<String, Account> getUpdatedAccounts() {
    Map<String, Account> accountMap = new Map<String, Account>();
    for (Account a : [
      SELECT
        Id,
        Name,
        Balancing_Amount__c,
        Total_Transfers_In__c,
        Total_Transfers_Out__c,
        Total_Card_Charges__c,
        Total_Charges_Stricken__c,
        Balance__c
      FROM Account
    ]) {
      accountMap.put(a.Name, a);
    }
    return accountMap;
  }
}