force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>Overall balance of the account.</description>
    <formula>(Total_Income__c +  Total_Transfers_In__c) - (Total_Expenses__c + Total_Transfers_Out__c + Total_Card_Charges__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Balancing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balancing_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount to offset calculations by for the balance total due to omitted or previously removed transfer, expense, or income records.(i.e. initial balance, balance after removing old records to clear up storage, etc.)</description>
    <label>Balancing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Object for tracking an incurred expense.</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the expense was incurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <description>Object for tracking income received.</description>
    <label>Income</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the income was received.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <description>A record that does not indicate an expense incurred or income received but which facilitates a balance transfer from one account to another.</description>
    <label>Transfer</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the transfer occurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TransactionCleanupService.cls
public with sharing class TransactionCleanupService {
  public static void run() {
    // get all accounts with subtotals fields before deleting old records
    // gather expenses more than 12 months old
    // gather incomes more than 12 months old
    // gather transfers more than 12 months old
    // delete expenses
    // delete incomes
    // delete transfers
    // get all accounts again
    // compare balances and correct for differences with balancing amount
    Date oneYearAgo = System.today().addYears(-1);
    List<SObject> recordsToDelete = new List<SObject>();
    Map<Id, Account> accountsPre = getAccounts();

    List<Expense__c> expenses = getExpenses(oneYearAgo);
    List<Income__c> incomes = getIncomes(oneYearAgo);
    List<Transfer__c> transfers = getTransfers(oneYearAgo);

    recordsToDelete.addAll(expenses);
    recordsToDelete.addAll(incomes);
    recordsToDelete.addAll(transfers);

    delete as system recordsToDelete;

    Map<Id, Account> accountsPost = getAccounts();
    Map<Id, Account> accountsToUpdate = accountsPost.deepClone();

    for (Id accId : accountsPost.keySet()) {
      Double balanceBefore = accountsPre.get(accId).Balance__c;
      Double balanceAfter = accountsPost.get(accId).Balance__c;
      Double balanceDifference = balanceBefore - balanceAfter;
      accountsToUpdate.get(accId).Balancing_Amount__c += balanceDifference;
    }

    update as system accountsToUpdate.values();
  }

  public static Map<Id, Account> getAccounts() {
    return new Map<Id, Account>(
      [SELECT Id, Name, Balance__c, Balancing_Amount__c FROM Account WITH SYSTEM_MODE]
    );
  }

  private static List<Expense__c> getExpenses(Date dateParam) {
    return [
      SELECT Id
      FROM Expense__c
      WHERE Date__c < :dateParam
      WITH SYSTEM_MODE
    ];
  }

  private static List<Income__c> getIncomes(Date dateParam) {
    return [
      SELECT Id
      FROM Income__c
      WHERE Date__c < :dateParam
      WITH SYSTEM_MODE
    ];
  }

  private static List<Transfer__c> getTransfers(Date dateParam) {
    return [
      SELECT Id
      FROM Transfer__c
      WHERE Date__c < :dateParam
      WITH SYSTEM_MODE
    ];
  }
}