force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>Overall balance of the account.</description>
    <formula>(Total_Income__c +  Total_Transfers_In__c) - (Total_Expenses__c + Total_Transfers_Out__c + Total_Card_Charges__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Balancing_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balancing_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount to offset calculations by for the balance total due to omitted or previously removed transfer, expense, or income records.(i.e. initial balance, balance after removing old records to clear up storage, etc.)</description>
    <label>Balancing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>Object for tracking an incurred expense.</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expense ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the expense was incurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Give a quick subject/title of the expense.</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income__c/Income__c.object-meta.xml
<CustomObject>
    <description>Object for tracking income received.</description>
    <label>Income</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Income Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Income__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the income was received.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Income__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>A brief description of the income received.</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <description>A record that does not indicate an expense incurred or income received but which facilitates a balance transfer from one account to another.</description>
    <label>Transfer</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date the transfer occurred.</description>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TransactionCleanupServiceTest.cls
@IsTest
private with sharing class TransactionCleanupServiceTest {
  private static final User ME = new User(Id = UserInfo.getUserId());
  private static final Date LONGAGO = System.today().addMonths(-15);

  @TestSetup
  static void testSetup() {
    System.runAs(ME) {
      TestDataFactory.setupScheduledServiceTestData();
    }
  }

  @isTest
  static void transactionCleanupServiceTest() {
    Map<String, Account> actualPre = new Map<String, Account>();
    Map<String, Account> actualPost = new Map<String, Account>();
    for (Account a : TransactionCleanupService.getAccounts().values()) {
      actualPre.put(a.Name, a);
    }
    Map<String, Map<String, Double>> expectedPre = new Map<String, Map<String, Double>>{
      'test_checking' => new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Balance__c' => 1690
      },
      'test_savings' => new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Balance__c' => 410
      },
      'test_card' => new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Balance__c' => 75
      },
      'test_cash' => new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Balance__c' => 415
      },
      'test_digital' => new Map<String, Double>{
        'Balancing_Amount__c' => 100,
        'Balance__c' => 270
      }
    };

    assertBalances(actualPre, expectedPre);

    Test.startTest();
    String jobId;
    List<SObject> allRecordsToDelete = new List<SObject>();
    System.runAs(ME) {
      for (Income__c i : [
        SELECT Id, Date__c
        FROM Income__c
        WHERE
          Subject__c IN (
            'employment_income_1',
            'gig_income_1',
            'gig_income_2',
            'employment_income_3'
          )
      ]) {
        i.Date__c = LONGAGO;
        allRecordsToDelete.add(i);
      }
      for (Expense__c e : [
        SELECT Id, Date__c
        FROM Expense__c
        WHERE
          Subject__c IN (
            'card_expense_1',
            'checking_expense_1',
            'card_expense_3',
            'cash_expense_1'
          )
      ]) {
        e.Date__c = LONGAGO;
        allRecordsToDelete.add(e);
      }
      for (Transfer__c t : [
        SELECT Id, Date__c
        FROM Transfer__c
        WHERE
          Subject__c IN (
            'lateral_transfer_1',
            'stricken_transfer_1',
            'atm_transfer_2',
            'lateral_transfer_3'
          )
      ]) {
        t.Date__c = LONGAGO;
        allRecordsToDelete.add(t);
      }
    }

    update allRecordsToDelete;

    jobId = TransactionCleanupScheduler.schedule(
      'myUniqueStringForTesting' + String.valueOf(Math.random())
    );
    Test.stopTest();

    for (Account a : TransactionCleanupService.getAccounts().values()) {
      actualPost.put(a.Name, a);
    }
    Map<String, Map<String, Double>> expectedPost = new Map<String, Map<String, Double>>{
      'test_checking' => new Map<String, Double>{
        'Balancing_Amount__c' => 1550,
        'Balance__c' => 1690
      },
      'test_savings' => new Map<String, Double>{
        'Balancing_Amount__c' => 400,
        'Balance__c' => 410
      },
      'test_card' => new Map<String, Double>{
        'Balancing_Amount__c' => 260,
        'Balance__c' => 75
      },
      'test_cash' => new Map<String, Double>{
        'Balancing_Amount__c' => 205,
        'Balance__c' => 415
      },
      'test_digital' => new Map<String, Double>{
        'Balancing_Amount__c' => 250,
        'Balance__c' => 270
      }
    };

    assertBalances(actualPost, expectedPost);

    Assert.isTrue(true, 'all asserts have passed; satisfy PMD');
  }

  static void assertBalances(
    Map<String, Account> actuals,
    Map<String, Map<String, Double>> expecteds
  ) {
    for (String accName : actuals.keySet()) {
      Map<String, Double> expected = expecteds.get(accName);
      Account actual = actuals.get(accName);
      for (String field : expected.keySet()) {
        Assert.areEqual(
          expected.get(field),
          actual.get(field),
          'actual field value should match expected value for account: ' +
          accName
        );
      }
    }
  }
}