force-app/main/default/objects/Account/fields/Total_Card_Charges__c.field-meta.xml
<CustomField>
    <fullName>Total_Card_Charges__c</fullName>
    <description>Total paid off charges to credit cards from the account.</description>
    <label>Total Card Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_In__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_In__c</fullName>
    <label>Total Transfers In</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_Out__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_Out__c</fullName>
    <label>Total Transfers Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <description>A record that does not indicate an expense incurred or income received but which facilitates a balance transfer from one account to another.</description>
    <label>Transfer</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of the transfer.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Withdrawal</fullName>
            </value>
            <value>
                <fullName>Online Transfer</fullName>
            </value>
            <value>
                <fullName>Venmo Transfer</fullName>
            </value>
            <value>
                <fullName>Card Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Source_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outbound Transfers</relationshipLabel>
    <relationshipName>Outbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Target_Account__c.field-meta.xml
<CustomField>
    <fullName>Target_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbound Transfers</relationshipLabel>
    <relationshipName>Inbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static Account CreateOneGeneralAccount(String accNum, String accName) {
        Account acc = new Account(
            AccountNumber = 'General' + accNum,
            Type = 'Checking Account',
            RecordTypeId = '012Dn000000tIWQIA2',
            Name = 'Test General Account ' + accName,
            Total_Transfers_In__c = 100,
            Total_Transfers_Out__c = 25,
            Total_Card_Charges__c = 25
        );
        insert acc;
        return acc;
    }
    
    public static Account CreateOneCreditCardAccount(String accName) {
        Account acc = new Account(
            AccountNumber = '456xyz credit',
            Type = 'Credit Card',
            RecordTypeId = '012Dn000000tIWLIA2',
            Name = 'Test Credit Card Account ' + accName,
            Total_Transfers_Out__c = 25
        );
        insert acc;
        return acc;
    }

    private static Map<Account, Account> createTestAccountPairs(Integer numPairs) {
        Map<Account, Account> sourceTargetPairs = new Map<Account, Account>();
        for (Integer i = 0; i < numPairs; i++) {
            sourceTargetPairs.put(
                new Account(
                    AccountNumber = i.format().repeat(4),
                    Name = 'Test Source Account ' + (i+1).format(),
                    Total_Transfers_In__c = 300,
                    Total_Transfers_Out__c = 300
                ),
                new Account(
                    AccountNumber = (i+1).format().repeat(4),
                    Name = 'Test Target Account ' + (i+1).format(),
                    Total_Transfers_In__c = 300,
                    Total_Transfers_Out__c = 300
                )
            );
        }
        System.debug('new lists of accounts: source list: ' + sourceTargetPairs.keySet() + '; target list: ' + sourceTargetPairs.values());
        try {
            insert new List<Account>(sourceTargetPairs.keySet());
            insert new List<Account>(sourceTargetPairs.values());
        } catch (DmlException exc) {
            System.debug('could not insert test accounts: ' + exc);
        }
        System.debug('sourceTargetPair: ' + sourceTargetPairs);
        return sourceTargetPairs;
    }

    public static Transfer__c createOneTransfer(
            Account source, 
            Account target, 
            Integer amount, 
            String transferName,
            String method
        ) {
        Transfer__c transfer = new Transfer__c(
            Amount__c = amount,
            Source_Account__c = source.Id,
            Target_Account__c = target.Id,
            Subject__c = transferName,
            Method__c = method
        );
        return transfer;
    }
    
    // public static List<Transfer__c> createMultipleTransfers(Map<Account, Account> AccountMap) {
    //     List<Transfer__c> newTransfers = new List<Transfer__c>();
    //     Integer amt = 100;
    //     for (Account a : AccountMap.keySet()) {
    //         Integer i = 0;
    //         newTransfers.add(new Transfer(
    //             Amount__c = amt,
    //             RecordTypeId = (math.mod(i,2)==0) ? '012Dn000000tI9JIAU' : '012Dn000000tI9EIAU',
    //             Source_Account__c = a.Id,
    //             Target_Account__c = AccountMap.get(a).Id,
    //             Subject__c = 'Test Transfer Record ' + (i+1).format()
    //         ));
    //         amt += 50;
    //         I += 1;
    //     }
    // }
}