force-app/main/default/objects/Account/fields/Total_Card_Charges__c.field-meta.xml
<CustomField>
    <fullName>Total_Card_Charges__c</fullName>
    <description>Total paid off charges to credit cards from the account.</description>
    <label>Total Card Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_In__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_In__c</fullName>
    <label>Total Transfers In</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Transfers_Out__c.field-meta.xml
<CustomField>
    <fullName>Total_Transfers_Out__c</fullName>
    <label>Total Transfers Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transfer__c/Transfer__c.object-meta.xml
<CustomObject>
    <description>A record that does not indicate an expense incurred or income received but which facilitates a balance transfer from one account to another.</description>
    <label>Transfer</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of the transfer.</description>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATM Withdrawal</fullName>
            </value>
            <value>
                <fullName>Online Transfer</fullName>
            </value>
            <value>
                <fullName>Venmo Transfer</fullName>
            </value>
            <value>
                <fullName>Card Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Source_Account__c.field-meta.xml
<CustomField>
    <fullName>Source_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outbound Transfers</relationshipLabel>
    <relationshipName>Outbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer__c/fields/Target_Account__c.field-meta.xml
<CustomField>
    <fullName>Target_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbound Transfers</relationshipLabel>
    <relationshipName>Inbound_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TransferTriggerController.cls
public class TransferTriggerController {
    
    public static void addNewTransfers(List<Transfer__c> transfersFromTrigger) {
        List<Map<Id,Account>> relatedAccounts = getRelatedAccounts(transfersFromTrigger);
        Map<Id, Account> SourceAccountsMap = relatedAccounts[0];
        Map<Id, Account> TargetAccountsMap = relatedAccounts[1];

        for (Transfer__c t : transfersFromTrigger) {

            // card payoffs
            if (t.Method__c == 'Card Payoff') {
                if (t.Source_Account__c != null) {
                    SourceAccountsMap.get(t.Source_Account__c).Total_Card_Charges__c += t.Amount__c;
                }
                TargetAccountsMap.get(t.Target_Account__c).Total_Transfers_In__c += t.Amount__c;
            }
            // lateral transfers
            else {
                if (t.Source_Account__c != null) {
                    SourceAccountsMap.get(t.Source_Account__c).Total_Transfers_Out__c += t.Amount__c;
                }
                TargetAccountsMap.get(t.Target_Account__c).Total_Transfers_In__c += t.Amount__c;
            }
        }
        
        List<Account> accountsToUpdate = new List<Account>();
        accountsToUpdate.addAll(SourceAccountsMap.values());
        accountsToUpdate.addAll(TargetAccountsMap.values());
        update accountsToUpdate;
    }

    public static void revertPriorTransfers(List<Transfer__c> transfersFromTrigger) {
        List<Map<Id,Account>> relatedAccounts = getRelatedAccounts(transfersFromTrigger);
        Map<Id, Account> SourceAccountsMap = relatedAccounts[0];
        Map<Id, Account> TargetAccountsMap = relatedAccounts[1];

        for (Transfer__c t : transfersFromTrigger) {

            // undo card payoffs
            
        }
    }

    private static List<Map<Id,Account>> getRelatedAccounts(List<Transfer__c> transfers) {
        List<Id> SourceAccountIds = new List<Id>();
        List<Id> TargetAccountIds = new List<Id>();

        // get lists of source and target account IDs
        for (Transfer__c t : transfers) {
            SourceAccountIds.add(t.Source_Account__c);
            TargetAccountIds.add(t.Target_Account__c);
        }
        
        // get all source and target account records
        Map<Id, Account> SourceAccountsMap = new Map<Id, Account>(
            [SELECT Id, Total_Transfers_In__c, Total_Transfers_Out__c, Total_Card_Charges__c, Type
             FROM Account
             WHERE Id IN :SourceAccountIds]
        );
        Map<Id, Account> TargetAccountsMap = new Map<Id, Account>(
            [SELECT Id, Total_Transfers_In__c, Total_Transfers_Out__c, Total_Card_Charges__c, Type
             FROM Account
             WHERE Id IN :TargetAccountIds]
        );
        
        return new List<Map<Id,Account>>{SourceAccountsMap, TargetAccountsMap};
    }
}